### ISSUE TITLE
Bundletool error: Error: Program type already present

### ISSUE THREAD

**Issue by archdanny** [bitrise-steplib/steps-deploy-to-bitrise-io#114] opened 2020-01-02 10:52 UTC
Hi,

I'm getting a "Error: Program type already present" following error while creating a universal APK from an AAB.

Other users are also encountering this issue. 
https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/109

The bug is related to the older bundletool version being used, v0.9.0. The issue has ben fixed in newer versions. 
https://github.com/google/bundletool/issues/113
Can the bundletool version be updated in bundletool.go 

The error: 
`java "-jar" "/tmp/tool194485974/bundletool-all-0.9.0.jar" "build-apks" "--mode=universal" "--bundle" "/bitrise/deploy/app.aab" "--output" "/tmp/aab-bundle5885/universal.apks" "--ks" "/tmp/aab-bundle5885/debug.keystore" "--ks-pass" "pass:android" "--ks-key-alias" "androiddebugkey" "--key-pass" "pass:android" failed (status: 1): Error: Program type already present: $r8$java8methods$utility$Integer$hashCode$II
[BT:0.9.0] Error: Dex merging failed.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Dex merging failed.
	at com.android.tools.build.bundletool.mergers.D8DexMerger.translateD8Exception(D8DexMerger.java:98)
	at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:77)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFiles(ModuleSplitsToShardMerger.java:333)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.lambda$mergeDexFilesAndCache$3(ModuleSplitsToShardMerger.java:300)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeDexFilesAndCache(ModuleSplitsToShardMerger.java:298)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.mergeSingleShard(ModuleSplitsToShardMerger.java:192)
	at com.android.tools.build.bundletool.mergers.ModuleSplitsToShardMerger.merge(ModuleSplitsToShardMerger.java:106)
	at com.android.tools.build.bundletool.splitters.BundleSharder.shardBundle(BundleSharder.java:102)
	at com.android.tools.build.bundletool.splitters.ShardedApksGenerator.generateSplits(ShardedApksGenerator.java:68)
	at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:200)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:486)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.tools.build.bundletool.mergers.D8DexMerger.merge(D8DexMerger.java:70)
	... 12 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
	... 15 more`

**Comment by non-binary** [comment] 2020-01-02 18:35
Hi @archdanny,

Thanks for reaching out.

I'll look into this and draft a pull request for our engineering team to consider.

Thanks,
Luna

**Comment by non-binary** [comment] 2020-01-03 13:43
Hi @archdanny,

Thank you for your patience.

As you can see, I've filed a pull request for this change and forwarded it on to our tooling team so they can check it out and approve it for merge.

Please don't hesitate to follow-up if you have any questions in the meantime.

Cheers,
Luna

**Comment by archdanny** [comment] 2020-01-05 23:30
Hi Luna,

Thnx for the pull request

**Comment by non-binary** [comment] 2020-01-07 14:30
Hi @archdanny,

Thank you for your patience.

The Bitrise tooling team has confirmed with me that have a JIRA Issue for my pull request and will check it in the next sprint.

Until then, if you want to use the fix, you can run the step from my branch with the fix by following the steps found in [this guide](https://devcenter.bitrise.io/steps-and-workflows/adding-removing-steps/#adding-steps-from-alternative-sources).

Happy to answer any other questions as well.

Kind regards,
Luna

**Comment by archdanny** [comment] 2020-01-11 18:02
Hi Luna, 

We're already using a fork I made with the updated bundletool version.
Great to hear that the PR (LGTM) wil be checked next sprint. 

Regards,

Daniello

**Comment by androideveloper** [comment] 2020-05-28 06:35
Hi Luna,

We are also experiencing an issue because bundletool is out of date.
A PR is created for this https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/pull/122

Best,
Roland

**Comment by non-binary** [comment] 2020-06-04 14:43
Hi @androideveloper,

I see that the pull request has been merged. Please let us know if you have any other questions.

**Closed by non-binary** 2020-06-04 14:43 UTC
